---
repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: ^docker-compose.*.yml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace

-   repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
    -   id: black
        args: [--safe]
        language_version: python3.6
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==18.9b0]
        language_version: python3.6
